version: '3.9'

services:
  nuxt:
    build: docker/nuxt3
    volumes:
      - ./front:/app:cached
      - ./front/node_modules:/app/node_modules:cached
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /home/${USERNAME}:/home/${USERNAME}
    ports:
      - "${MYIP}:30001:3000"
      - "${MYIP}:24600:24600"
    user: "${UID}:${GID}"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - CHOKIDAR_USERPOLLING=true
    command: sh -c "npm install && npm run dev"
